library(arules)
library(arulesViz)
df <- read.csv("unix.csv")
head(df)
?apriori
rules <- apriori(df, parameter = list(minlen=2, support=0.01, confidence=0.5))
inspect(head(rules))
inspect(sort(rules, by ="lift"))
inspect(sort(rules, by ="confidence"))
plot(rules)